version: '3'

networks:
  fullcycle:
    driver: bridge

services:

  app:
    build:
      context: ./app
    container_name: app
    networks:
      - fullcycle
    tty: true
    volumes:
      - ./app:/usr/src/app
    depends_on:
      database:
        condition: "service_healthy"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      - app

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mysql:
    driver: local
