version: '3'

networks:
  fullcycle:
    driver: bridge

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: sh -c "npm install && node index.js"
    networks:
      - fullcycle
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      database:
        condition: "service_healthy"

  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      - app
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql:
    driver: local